#!/bin/env bash

# _apt_logger
# This function is a wrapper around apt and apt-get that logs the command to /var/log/apt.log
# so that we can track what was installed and when.
_apt_logger() {
  set -x && trap 'set +x' EXIT
  "${@}"
  _code="${?}"
  if [ "${_code}" -eq 0 ] && [ "$UID" -eq 0 ]; then
    local _command=""
    if [ "${#}" -gt 1 ]; then
      _command="${2}"
    fi
    case "$_command" in
      install | upgrade | remove | build-dep)
        printf "%s\t%s" "$(date)" "${*}" >> /var/log/apt.log
        ;;
      *) ;; # we don't care probably
    esac
  fi
  return "${_code}"
}

alias apt="_apt_logger apt"
alias apt-get="_apt_logger apt-get"
