# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#  geometry symbols: , , ,   (these all live in the E0B0+ range

# Global Configuration
add_newline = false
command_timeout = 500
scan_timeout = 30
follow_symlinks = true
palette = "ristretto"

format = """\
[](fg:red)\
$os\
$hostname\
[](fg:red bg:orange)\
$container\
$directory\
[](fg:orange bg:yellow)\
$git_branch\
$git_status\
$git_metrics\
[](fg:yellow bg:blue)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:blue bg:base2)\
$character\
[](fg:base2)\
"""

right_format  = """\
$status\
$sudo\
${custom.env_file}\
${custom.poetry_env}\
[ ](fg:base3)\
$python\
[ ](fg:base6 bg:base3)\
$kubernetes\
[ ](fg:base7 bg:base6)\
$time\
[](fg:base7)\
"""

[character]
success_symbol = "[ ](fg:dark_green)"
error_symbol = "[❌](fg:red)"

[os]
disabled = false
style = "fg:blue bg:red"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰖳 "
Linux = "󰌽 "
Macos = "󰀵"

[python]
version_format = "${raw}"
style = "fg:base7 bg:base3"
format = "[$version:$virtualenv]($style)"
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", ".python-version"]
detect_folders = []

[status]
disabled = false
style = "fg:red bold strikethrough"
symbol = ""
format = "[$symbol$status]($style)"

[sudo]
disabled = false
style = "fg:purple bold"
symbol = "🧙"
format = "[$symbol]($style)"

[container]
disabled = false
style = "fg:base8 bg:orange"
symbol = ""
format = "[$symbol ]($style)"

[custom.env_alert]
detect_files = [".env"]
symbol = " "
style = "fg:yellow blink"
#format

[custom.poetry_env]
when = """
! {[[ "$VIRTUAL_ENV" == *pypoetry* ]] ||  env=$(poetry env info -p 2>/dev/null) && [[ "$(which python)" == *"$env"* ]]}
"""
style = "blink"
symbol = "🐍"
format = "[$symbol]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:base8x0c  bg:base7"
format = '[ $time ]($style)'


[kubernetes]
disabled = false
style = "fg:base8 bg:base6"
symbol = ""
format = "[$symbol $context( ($namespace))]($style)"

[kubernetes.context_aliases]
"local" = "⛵ "

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:red fg:base0"
style_root = "bg:red fg:base0"
format = '[$user ]($style)'

[hostname]
ssh_only = false
ssh_symbol = "☎️"
style = "bg:red fg:base0"
format = "[$hostname $ssh_symbol]($style)"

[directory]
style = "fg:base1 bg:orange"
repo_root_style  =  "fg:base8 bg:orange"
read_only = "  "
read_only_style =  "fg:purple bg:orange"
repo_root_format = "[ $before_root_path]($style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/Code" = " "
"/home/redshred" = " "
"~/Code/redshred" = " "


[c]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:base2 bg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:base2 bg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
disabled = false
added_style = "fg:dark_green bg:yellow"
deleted_style = "fg:dark_red bg:yellow"
format = '([+$added ]($added_style)[-$deleted ]($deleted_style))'

[golang]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[nodejs]
# get rid of node_modules since I don't want this  on the home screen
detect_folders = []
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'

# Color Palette Definition
[palettes.ristretto]
# primary colors
red = "#fd6883"
dark_red = "#AA0D00"
orange = "#f38d70"
yellow = "#f9cc6c"
green = "#adda78"
dark_green = "#008F0C"
blue = "#85dacc"
purple = "#a8a9eb"
# base colors
base0 = "#191515"
base1 = "#211c1c"
base2 = "#2c2525"
base3 = "#403838"
base4 = "#5b5353"
base5 = "#72696a"
base6 = "#8c8384"
base7 = "#c3b7b8"
base8 = "#fff1f3"
# variants
base8x0c = "#352e2e"